---
# tasks file for roles/win_ad_install
- name: Install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes

- name: Set up the AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: ad_controller

- name: Reboots the instance
  win_reboot:
  when: ad_controller.reboot_required

- name: Print out the domain list
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
    var: domain_list
...
